/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as ImproveRouteImport } from './routes/improve'
import { Route as EmailRouteImport } from './routes/email'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAiRouteImport } from './routes/api/ai'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const ImproveRoute = ImproveRouteImport.update({
  id: '/improve',
  path: '/improve',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiRoute = ApiAiRouteImport.update({
  id: '/api/ai',
  path: '/api/ai',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/email': typeof EmailRoute
  '/improve': typeof ImproveRoute
  '/meetings': typeof MeetingsRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/templates': typeof TemplatesRoute
  '/workspace': typeof WorkspaceRoute
  '/api/ai': typeof ApiAiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/email': typeof EmailRoute
  '/improve': typeof ImproveRoute
  '/meetings': typeof MeetingsRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/templates': typeof TemplatesRoute
  '/workspace': typeof WorkspaceRoute
  '/api/ai': typeof ApiAiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/email': typeof EmailRoute
  '/improve': typeof ImproveRoute
  '/meetings': typeof MeetingsRoute
  '/research': typeof ResearchRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/templates': typeof TemplatesRoute
  '/workspace': typeof WorkspaceRoute
  '/api/ai': typeof ApiAiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/email'
    | '/improve'
    | '/meetings'
    | '/research'
    | '/settings'
    | '/tasks'
    | '/templates'
    | '/workspace'
    | '/api/ai'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/email'
    | '/improve'
    | '/meetings'
    | '/research'
    | '/settings'
    | '/tasks'
    | '/templates'
    | '/workspace'
    | '/api/ai'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/email'
    | '/improve'
    | '/meetings'
    | '/research'
    | '/settings'
    | '/tasks'
    | '/templates'
    | '/workspace'
    | '/api/ai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  EmailRoute: typeof EmailRoute
  ImproveRoute: typeof ImproveRoute
  MeetingsRoute: typeof MeetingsRoute
  ResearchRoute: typeof ResearchRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  TemplatesRoute: typeof TemplatesRoute
  WorkspaceRoute: typeof WorkspaceRoute
  ApiAiRoute: typeof ApiAiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/improve': {
      id: '/improve'
      path: '/improve'
      fullPath: '/improve'
      preLoaderRoute: typeof ImproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai': {
      id: '/api/ai'
      path: '/api/ai'
      fullPath: '/api/ai'
      preLoaderRoute: typeof ApiAiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  EmailRoute: EmailRoute,
  ImproveRoute: ImproveRoute,
  MeetingsRoute: MeetingsRoute,
  ResearchRoute: ResearchRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  TemplatesRoute: TemplatesRoute,
  WorkspaceRoute: WorkspaceRoute,
  ApiAiRoute: ApiAiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
